export  {default as Header} from "./Header.jsx"
export  {default as Hero} from "./Hero.jsx"
export  {default as WhatGPT4} from "./WhatGPT4.jsx"
export  {default as About} from "./About.jsx"
export  {default as Features} from "./Features.jsx"
export  {default as Blog} from "./Blog.jsx"
export  {default as Cta} from "./Cta.jsx"
export  {default as Footer} from "./Footer.jsx"
export  {default as Request} from './Request'
